### ISSUE TITLE
Deletes items if inventory is full.

### ISSUE THREAD

**Issue by DranDivine** [mike-brady/factorio-ghost-mode#1]
If I have a full inventory, and choose an item I have of in my inventory while ghost mode is active, it deletes the stack held. Also the case if I choose the item first, and then enables ghost mode with the item in cursor.

**Comment by mike-brady** [comment]
Hi, thanks for finding this! I just fixed it and published an update.

**Comment by DranDivine** [comment]
I was really surprised when I saw the update for it and how quick you were
at fixing it. Hahaha.
