### ISSUE TITLE
New crash.

### ISSUE THREAD

**Issue by DranDivine** [mike-brady/factorio-ghost-mode#3]
I have another crash. Seems to be caused if I have something selected in remote view while toggling off ghost mode. Just came by it by accident.
```6326.390 Error MainLoop.cpp:1429: Exception at tick 10457096: The mod Ghost Mode (2.1.1) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event ghost-mode::ghost_mode_toggle_custom_input (ID 219)
__ghost-mode__/control.lua:16: attempt to index a nil value
stack traceback:
	__ghost-mode__/control.lua:16: in function 'ghost_to_stack'
	__ghost-mode__/control.lua:32: in function 'toggle_ghost_mode'
	__ghost-mode__/control.lua:41: in function <__ghost-mode__/control.lua:39>

**Comment by mike-brady** [comment]
Fixed! It no longer crashes when you toggle off ghost mode in remote view. Just a note though, that when in remote view, the game only let's you build with ghosts as far as I can tell. So turning off ghost mode wont change the item in your hand from a ghost to a regular item. But once you leave remote view your item will switch back to a regular item if you have it in your inventory.

**Comment by DranDivine** [comment]
The reason I toggled ghost mode in remote view was because I was placing
rails, and I was trying to switch rail layer, while I was still holding
shift when I forgot to let go of it. :p
